### ISSUE TITLE
Add Stop animation in object

### ISSUE THREAD

**Issue by driedel-zz** [lmgonzalves/segment#12]
I'm using segment to make a countdown, and if I skip the item before the animation end it still counting. If I come back to the item and try to start from zero the plugin ignores because the animationTimer still running.

I put  the stop function visible to the object and use it to reset the counter... works perfectly :)

**Comment by lmgonzalves** [comment]
Hi, thanks for contributing!
Please help me understand this, because `stop` function is actually public. So, you don't need:

``` js
this.stop = this.stop;
```

But seems a good idea to call `stop` in the constructor instead setting `timer` and `animationTimer` to `null`. Something like:

``` js
this.draw(this.begin, this.end, 0, {circular: this.circular});
this.stop();
```

**Comment by driedel-zz** [comment]
Hi :)

I'm sorry, I suggest something that already works :(

I was trying to stop just setting the .draw to zero, but it doesn't stop the animation... so I look at your code the stop function and don't try to call it because it was not listed in the constructor..

I've made an example in JSFiddle, and it works perfectly.

https://fiddle.jshell.net/driedel/fcmy8dq9/

Look at the updateTimer function and you will understand my mistake.

**Comment by lmgonzalves** [comment]
mmm, I see.
Ok, I will document `stop` function in README as soon as possible :)
Thanks!
