### ISSUE TITLE
adding tags for the repo

### ISSUE THREAD

**Issue by Amomo** [lmgonzalves/segment#4]
Hello, 

Adding tags for repo could specify points in history and mark release points.
It's helpful for user to know the version and status of repository, and would enable wider distribution of the library, for example it could be hosted by [cdnjs](https://github.com/cdnjs/cdnjs) ([website](https://cdnjs.com/))

Would you please consider on using tags?
Thanks for your great work!

**Comment by lmgonzalves** [comment]
Hello there!

Right now I'm a little off for Christmas, but I will work in January to facilitate working with Segment, using the most popular ways (CDNs, Node, Bower, etc.).

Please stay tuned! And thank you very much for your words :)

**Comment by lmgonzalves** [comment]
I've added a tag for version `1.0.0`, the library is stable and ready for use in production. Please let me know if something else is needed. And thanks for help distributing `segment` :)
