### ISSUE TITLE
'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by shahjehanali1** [lmgonzalves/segment#9]
`$('.service-section').each(function() {
        var el = $(this);
        var topDistance = $(this).offset().top - $(window).height() + 200;
        if ( (topDistance) < scrollTop ) {
            var myPath = document.getElementById("glob"),
            segment = new Segment(myPath);

```
        segment.draw("25%", "75% - 10", 1);
    }
});`
```

this code showing me an error 'hasOwnProperty' of undefined

**Comment by lmgonzalves** [comment]
The code seems fine so far. Can you recreate the issue in [jsfiddle](http://jsfiddle.net/) or [codepen](http://codepen.io/), so I can see the whole code and find a solution?
